# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  ASDF_MAGE_VERSION: '1.15.0'

steps:
  - label: "Generate dynamic pipeline"
    command: ".buildkite/scripts/generate_pipeline.sh"
    agents:
      provider: gcp
      imageProject: elastic-images-prod
      image: family/platform-ingest-beats-ubuntu-2204
      machineType: "n2-standard-2"
